//USER REDUCER CONSTANTS
export const NEW_USER = 'NEW_USER';

//TEST REDUCER CONSTANTS
export const NEW_TEST = 'NEW_TEST';
export const DELETE_TEST = 'DELETE_TEST';

//CURRENT TEST REDUCER CONSTANTS
export const NEW_CURRENT_TEST = 'NEW_CURRENT_TEST';
export const RESET_CURRENT_TEST = 'RESET_CURRENT_TEST';
export const ADD_MEMORY_TEST_RESULT = 'ADD_MEMORY_TEST_RESULT';
export const ADD_REACTIONTIME_TEST_RESULT = 'ADD_REACTION_TIME_TEST_RESULT';

//TEST SCRIPT REDUCER CONSTANTS
export const ADVANCE_TEST_SCRIPT = 'ADVANCE_TEST_SCRIPT';
export const RESTART_TEST_SCRIPT = 'RESTART_TEST_SCRIPT';
