//USER REDUCER CONSTANTS
export const NEW_USER = 'NEW_USER';

//TEST REDUCER CONSTANTS
export const NEW_TEST = 'NEW_TEST';
export const DELETE_TEST = 'DELETE_TEST';

//CURRENT TEST REDUCER CONSTANTS
export const NEW_CURRENT_TEST = 'NEW_CURRENT_TEST';

//TEST SCRIPT REDUCER CONSTANTS
export const ADVANCE_TEST_SCRIPT = 'ADVANCE_TEST_SCRIPT';
export const RESTART_TEST_SCRIPT = 'RESTART_TEST_SCRIPT';